pipeline:
  name: Harness-STO-Aqua-Trivy-2
  identifier: HarnessSTOAquaTrivy2
  projectIdentifier: VN
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: STO
        build: <+input>
  pipeline:
    name: Harness-STO-Aqua-Trivy-2
    identifier: HarnessSTOAquaTrivy2
    projectIdentifier: VN
    orgIdentifier: default
    tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: false
          sharedPaths:
            - /var/run
            - /shared/scan_results
          execution:
            steps:
              - step:
                  type: AquaTrivy
                  name: AquaTrivy_2
                  identifier: AquaTrivy_2
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: container
                      detection: manual
                      name: vikramtek/harness-sto-aqua-trivy:STO_Image
                      variant: docker
                    advanced:
                      log:
                        level: info
                      args:
                        cli: "--scanners vuln"
                    privileged: true
                    image:
                      type: docker_v2
                      tag: STO_Image
                      name: vikramtek/harness-sto-aqua-trivy
                      domain: index.docker.io
                    sbom:
                      format: spdx-json
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
          slsa_provenance:
            enabled: false
        description: ""
identifier: trivyorchestration
name: trivy-orchestration
